// <auto-generated />
using Backend.Models.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(StoryContext))]
    [Migration("20260328132225_MainCharacterName")]
    partial class MainCharacterName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Backend.Models.Db.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.ToTable("Nodes");

                    b.HasDiscriminator<string>("NodeType").HasValue("Node");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Backend.Models.Db.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MainCharacterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartingSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Structure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("Backend.Models.Db.QuestNode", b =>
                {
                    b.HasBaseType("Backend.Models.Db.Node");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserGoal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("QuestNode");
                });

            modelBuilder.Entity("Backend.Models.Db.StoryNode", b =>
                {
                    b.HasBaseType("Backend.Models.Db.Node");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentTurns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransitionTurns")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("StoryNode");
                });

            modelBuilder.Entity("Backend.Models.Db.Node", b =>
                {
                    b.HasOne("Backend.Models.Db.Story", "story")
                        .WithMany("Nodes")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("story");
                });

            modelBuilder.Entity("Backend.Models.Db.Story", b =>
                {
                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
